---
title: "midterm data"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 5
    #code_folding: hide
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=TRUE, error=TRUE)
```



```{r}

library(data.table)

all_data <- fread("https://raw.githubusercontent.com/CrumpLab/statisticsLab/master/data/SchroederEpley2015data.csv")


```

```{r}

library(dplyr)

```

```{r}

written <- all_data %>%
        filter(CONDITION == "0")

verbal <- all_data %>%
        filter(CONDITION == "1")

```

```{r}

verbal_mean_intellect <- verbal %>%
                summarise(mean(intellect))

written_mean_intellect <- written %>%
                summarise(mean(intellect))
```

```{r}

written_intellect <- c(2, 3, 2.666667, 4.666667, 6.666667, 4.666667, 1.666667, 5.666667, 4.666667, 8, 2.666667, 7.333333, 4.666667, 4.333333, 3.333333, 5.666667, 7.666667)
verbal_intellect <- c(6.638889, 5.577778, 5.577778, 5.888889, 5.577778, 5.888889, 5.577778, 5.722222, 5.888889, 5.577778, 5.722222, 5.888889, 5.722222, 5.577778, 5.722222, 5.577778, 5.888889, 5.888889)

#non-directional
my_ttest <- t.test(written_intellect, verbal_intellect, var.equal=TRUE)

my_ttest$p.value #there is a significant difference between verbal intellect and written intellect


mean(verbal_intellect)
sd(verbal_intellect)
```

```{r}

library(broom)

t_results <- t.test(written_intellect, verbal_intellect, var.equal=TRUE)
knitr::kable(tidy(t_results))

```

```{r}


plot_df <- data.frame(WI,VI)
# basic scatterplot
ggplot(plot_df, aes(x=WI,y=VI))+ #identify what x/y axis are, groups, etc connect data to different prts of graph
+   geom_point() #adds a layer of dots..


```

```{r}

library(ggplot2)
# Create dataframe

Intellect_perception <- c("verbal intellect","written intellect")
#hand entered all the data points, the general shapes replicate the ones from the homework

verbal_written_scores <- c(6.638889,2,5.577778,3,5.577778,2.666667,5.888889,4.666667,5.577778,6.666667,5.888889,4.666667,5.577778,1.666667,5.722222,5.666667,5.888889,4.666667,5.577778,8,5.722222,2.666667,5.888889,7.333333,5.722222,4.666667,5.577778,3.333333,4,5.722222,3.333333,5.577778,5.666667,7.666667)
  

#need to represent dots to follow equal then men, equal then men, to have an even number


plot_df <- data.frame(Intellect_perception,verbal_written_scores)



# basic scatterplot
ggplot(plot_df, aes(x=Intellect_perception,y=verbal_written_scores))+
   coord_cartesian(ylim=c(1,8))+#identify what x/y axis are, groups, etc connect data to different prts of graph
  geom_violin()#adds violin as representation of dots





```








